# fly.proxy.toml
app = 'garden-proxy'
primary_region = 'sea'

[build]
  dockerfile = "Dockerfile.proxy"

[processes]
  app = "npm run proxy:prod"

[http_service]
  internal_port = 8082
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[http_service.concurrency]
  type = "requests"
  hard_limit = 10
  soft_limit = 5

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
