# fly.toml
app = 'garden-summer-rain-983'
primary_region = 'sea'

[build]

[processes]
  app = "npm run ws"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"
