name: Fly Deploy
on:
  push:
    branches:
      - main
    paths:
      - 'server/**'
      - 'package.json'
      - 'package-lock.json'
      - 'fly.toml'
      - 'Dockerfile'
      - '.github/workflows/fly-deploy.yml'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
